author: SpleefLeague
authors: [JoBa97]
description: SpleefLeague Core Plugin
main: net.spleefleague.core.SpleefLeague
name: SpleefLeague
url: http://www.spleefleague.net/
version: 0.1
commands:
    test:
        description: Test command
        aliases: [testi]
        usage: |
          /<command> <player>
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
          /<command> <player> <rank>
    tell:
        description: A command
        aliases: []
        usage: |
          /<command> <player> <message>
    reply:
        description: A reply command
        aliases: [r]
        usage: |
          /<command> <message>
    gamemode:
        description: Sets a player's gamemode
        aliases: [gm]
        usage: |
          /<command> <gamemode> [player]
    warn:
        description: warn a player
        aliases: []
        usage: |
          /<command> <player> <message>
    kick:
        description: kick a player
        aliases: []
        usage: |
          /<command> <player> <message>
    tempban:
        description: tempban a player
        aliases: []
        usage: |
          /<command> <milliseconds> <player> <message>
    ban:
        description: ban a player
        aliases: []
        usage: |
          /<command> <player> <message>
    unban:
        description: unban a player
        aliases: []
        usage: |
          /<command> <player> <message>