author: SpleefLeague
authors: [JoBa97]
description: SpleefLeague Core Plugin
main: net.spleefleague.core.SpleefLeague
name: SpleefLeague
url: http://www.spleefleague.net/
version: 0.1
commands:
    test:
        description: Test command
        aliases: [testi]
        usage: |
          /<command> <player>
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
          /<command> <player> <rank>
    tell:
        description: A command
        aliases: []
        usage: |
          /<command> <player> <message>
    reply:
        description: A reply command
        aliases: [r]
        usage: |
          /<command> <message>