author: SpleefLeague
authors: [JoBa97]
description: SpleefLeague Core Plugin
main: net.spleefleague.core.SpleefLeague
name: SpleefLeague
url: http://www.spleefleague.net/
version: 0.1
commands:
    test:
        description: Test command
        aliases: [testi]
        usage: |
          /<command> <player>
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
          /<command> <player> <rank>
    reply:
        description: A reply command
        aliases: [r]
        usage: |
          /<command> <message>
    debug: 
        description: Load a debug class at runtime
        aliases: [d]
        usage:
            /<command> <hastebinId>
            /<command> cmd <debuggerId> <cmd> [args]
            /<command> stop <debuggerId>
    ping:
        description: Shows your own ping, or possibly that of another if you're helper+
        aliases: []
        usage:
            /<command> [username]