author: SpleefLeague
authors: [JoBa97]
description: SpleefLeague Core Plugin
main: net.spleefleague.core.SpleefLeague
name: SpleefLeague
url: http://www.spleefleague.net/
version: 0.1
commands:
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
          /<command> <player> <rank>
    reply:
        description: A reply command
        aliases: [r]
        usage: |
          /<command> <message>
    debug: 
        description: Load a debug class at runtime
        aliases: [d]
        usage:
            /<command> <hastebinId>
            /<command> cmd <debuggerId> <cmd> [args]
            /<command> stop <debuggerId>
    ping:
        description: Shows your own ping, or possibly that of another if you're helper+
        aliases: []
        usage:
            /<command> [username]
    gamemode:
        description: Sets a player's gamemode
        aliases: [gm]
        usage: |
          /<command> <gamemode> [player]
    warn:
        description: warn a player
        aliases: []
        usage: |
          /<command> <player> <message>
    kick:
        description: kick a player
        aliases: []
        usage: |
          /<command> <player> <message>
    tempban:
        description: tempban a player
        aliases: []
        usage: |
          /<command> <duration> <player> <message>
    ban:
        description: ban a player
        aliases: []
        usage: |
          /<command> <player> <message>
    unban:
        description: unban a player
        aliases: []
        usage: |
          /<command> <player> <message>
