author: SpleefLeague
authors: [JoBa97]
description: SpleefLeague Core Plugin
main: net.spleefleague.core.SpleefLeague
name: SpleefLeagueCore
url: http://www.spleefleague.net/
version: 0.1
commands:
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
          /<command> <player> <rank>
    reply:
        description: Reply to the last private message
        aliases: [r]
        usage: |
          /<command> <message>
    tell:
        description: A command to send a private message to a certain command
        aliases: [w, msg]
        usage: |
          /<command> <player> <message>
    debug: 
        description: Load a debug class at runtime
        aliases: [d,rd]
        usage:
            /<command> <hastebinId>
            /<command> cmd <debuggerId> <cmd> [args]
            /<command> stop <debuggerId>
    ping:
        description: Shows your own ping, or possibly that of another if you're helper+
        aliases: []
        usage:
            /<command> [username]
    gamemode:
        description: Sets a player's gamemode
        aliases: [gm]
        usage: |
          /<command> <gamemode> [player]
    warn:
        description: warn a player
        aliases: []
        usage: |
          /<command> <player> <message>
    kick:
        description: kick a player
        aliases: []
        usage: |
          /<command> <player> <message>
    tempban:
        description: tempban a player
        aliases: []
        usage: |
          /<command> <duration> <player> <message>
    ban:
        description: ban a player
        aliases: []
        usage: |
          /<command> <player> <message>
    unban:
        description: unban a player
        aliases: []
        usage: |
          /<command> <player> <message>
    surrender:
        description: surrenders the current game
        aliases: [ragequit]
        usage: |
          /<command>
    leave:
        description: Leaves the current queue
        aliases: [l]
        usage: |
          /<command>
    cancel:
        description: Cancels a game
        aliases: []
        usage: |
          /<command> <player>
    cancelall:
        description: Cancels every game
        aliases: []
        usage: |
          /<command>
    infractions:
        description: Displays the infractions of a player
        aliases: []
        usage: |
          /<command> <player> [page]
    spectate:
        description: Spectates a battle
        aliases: []
        usage: |
          /<command> [player]
    spawn:
        description: Teleports a player back to spawn
        aliases: []
        usage: |
          /<command>